version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: kidney-classification-backend
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    volumes:
      - ./Backend:/app
      - backend_artifacts:/app/artifacts
      - backend_model:/app/model
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kidney-network

  # React Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: kidney-classification-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - kidney-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: kidney-classification-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - kidney-network
    profiles:
      - production

volumes:
  backend_artifacts:
    driver: local
  backend_model:
    driver: local

networks:
  kidney-network:
    driver: bridge
